/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_7 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] sum,
    output reg z,
    output reg v,
    output reg n,
    output reg overflow
  );
  
  
  
  reg [16:0] holder;
  
  reg [15:0] negative;
  
  always @* begin
    negative = a - b;
    if (alufn[0+0-:1] == 1'h0) begin
      holder = a + b;
    end else begin
      holder = a - b;
    end
    sum = holder[0+15-:16];
    z = (~|holder);
    n = ~holder[15+0-:1];
    overflow = ((a[15+0-:1] & b[15+0-:1] & (~holder[15+0-:1])) | (~a[15+0-:1] & ~b[15+0-:1] & (holder[15+0-:1])));
    v = ((a[15+0-:1] & ~b[15+0-:1] & (~holder[15+0-:1])) | (~a[15+0-:1] & b[15+0-:1] & (holder[15+0-:1])));
  end
endmodule
