/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_3 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] alu,
    output reg z,
    output reg v,
    output reg n,
    output reg overflow
  );
  
  
  
  wire [16-1:0] M_add_sum;
  wire [1-1:0] M_add_z;
  wire [1-1:0] M_add_v;
  wire [1-1:0] M_add_n;
  wire [1-1:0] M_add_overflow;
  reg [16-1:0] M_add_a;
  reg [16-1:0] M_add_b;
  reg [6-1:0] M_add_alufn;
  adder_7 add (
    .a(M_add_a),
    .b(M_add_b),
    .alufn(M_add_alufn),
    .sum(M_add_sum),
    .z(M_add_z),
    .v(M_add_v),
    .n(M_add_n),
    .overflow(M_add_overflow)
  );
  
  wire [16-1:0] M_boole_bool;
  reg [4-1:0] M_boole_alufn;
  reg [16-1:0] M_boole_a;
  reg [16-1:0] M_boole_b;
  boolean_8 boole (
    .alufn(M_boole_alufn),
    .a(M_boole_a),
    .b(M_boole_b),
    .bool(M_boole_bool)
  );
  
  wire [16-1:0] M_comp_cmp;
  reg [6-1:0] M_comp_alufn;
  reg [1-1:0] M_comp_z;
  reg [1-1:0] M_comp_v;
  reg [1-1:0] M_comp_n;
  compare_9 comp (
    .alufn(M_comp_alufn),
    .z(M_comp_z),
    .v(M_comp_v),
    .n(M_comp_n),
    .cmp(M_comp_cmp)
  );
  
  wire [16-1:0] M_shift_result;
  reg [6-1:0] M_shift_alufn;
  reg [16-1:0] M_shift_a;
  reg [16-1:0] M_shift_b;
  shifter_10 shift (
    .alufn(M_shift_alufn),
    .a(M_shift_a),
    .b(M_shift_b),
    .result(M_shift_result)
  );
  
  wire [16-1:0] M_mul_out;
  reg [16-1:0] M_mul_a;
  reg [16-1:0] M_mul_b;
  reg [6-1:0] M_mul_alufn;
  multiplier_11 mul (
    .a(M_mul_a),
    .b(M_mul_b),
    .alufn(M_mul_alufn),
    .out(M_mul_out)
  );
  
  always @* begin
    M_add_a = a;
    M_add_b = b;
    M_add_alufn = alufn;
    M_boole_a = a;
    M_boole_b = b;
    M_boole_alufn = alufn;
    M_comp_alufn = alufn;
    M_comp_z = M_add_z;
    M_comp_v = M_add_v;
    M_comp_n = M_add_n;
    M_shift_a = a;
    M_shift_b = b;
    M_shift_alufn = alufn;
    M_mul_a = a;
    M_mul_b = b;
    M_mul_alufn = alufn;
    overflow = M_add_overflow;
    
    case (alufn[4+1-:2])
      2'h0: begin
        alu = M_add_sum;
        z = M_add_z;
        v = M_add_v;
        n = M_add_n;
      end
      2'h1: begin
        alu = M_boole_bool;
        z = 1'h0;
        v = 1'h0;
        n = 1'h0;
      end
      2'h2: begin
        alu = M_shift_result;
        z = 1'h0;
        v = 1'h0;
        n = 1'h0;
      end
      2'h3: begin
        alu = M_comp_cmp;
        z = 1'h0;
        v = 1'h0;
        n = 1'h0;
      end
      default: begin
        alu = 1'h0;
        z = 1'h0;
        v = 1'h0;
        n = 1'h0;
      end
    endcase
  end
endmodule
