/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_3 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] alu,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  wire [16-1:0] M_add_sum;
  wire [1-1:0] M_add_z;
  wire [1-1:0] M_add_v;
  wire [1-1:0] M_add_n;
  reg [16-1:0] M_add_a;
  reg [16-1:0] M_add_b;
  reg [6-1:0] M_add_alufn;
  adder_7 add (
    .a(M_add_a),
    .b(M_add_b),
    .alufn(M_add_alufn),
    .sum(M_add_sum),
    .z(M_add_z),
    .v(M_add_v),
    .n(M_add_n)
  );
  
  wire [1-1:0] M_boole_bool;
  reg [4-1:0] M_boole_alufn;
  reg [16-1:0] M_boole_a;
  reg [16-1:0] M_boole_b;
  boolean_8 boole (
    .alufn(M_boole_alufn),
    .a(M_boole_a),
    .b(M_boole_b),
    .bool(M_boole_bool)
  );
  
  wire [16-1:0] M_comp_result;
  reg [3-1:0] M_comp_alufn;
  reg [1-1:0] M_comp_z;
  reg [1-1:0] M_comp_v;
  reg [1-1:0] M_comp_n;
  compare_9 comp (
    .alufn(M_comp_alufn),
    .z(M_comp_z),
    .v(M_comp_v),
    .n(M_comp_n),
    .result(M_comp_result)
  );
  
  wire [16-1:0] M_shift_out;
  reg [16-1:0] M_shift_a;
  reg [16-1:0] M_shift_b;
  reg [6-1:0] M_shift_alufn;
  shifter_10 shift (
    .a(M_shift_a),
    .b(M_shift_b),
    .alufn(M_shift_alufn),
    .out(M_shift_out)
  );
  
  always @* begin
    M_add_a = a;
    M_add_b = b;
    M_add_alufn = alufn;
    M_boole_a = a;
    M_boole_b = b;
    M_boole_alufn = alufn;
    M_comp_alufn = alufn;
    M_comp_z = M_add_z;
    M_comp_v = M_add_v;
    M_comp_n = M_add_n;
    M_shift_a = a;
    M_shift_b = b;
    M_shift_alufn = alufn;
    if (alufn[4+0-:1] == 1'h0 && alufn[5+0-:1] == 1'h0) begin
      alu = M_add_sum;
    end else begin
      if (alufn[4+0-:1] == 1'h0 && alufn[5+0-:1] == 1'h1) begin
        alu = M_boole_bool;
      end else begin
        if (alufn[4+0-:1] == 1'h1 && alufn[5+0-:1] == 1'h0) begin
          alu = M_shift_out;
        end else begin
          if (alufn[4+0-:1] == 1'h1 && alufn[5+0-:1] == 1'h1) begin
            alu = M_comp_result;
          end else begin
            alu = 8'h00;
          end
        end
      end
    end
    z = M_add_z;
    v = M_add_v;
    n = M_add_n;
  end
endmodule
