/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_8 (
    input [3:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg bool
  );
  
  
  
  reg holder;
  
  always @* begin
    if (a == 1'h0 & b == 1'h0) begin
      holder = alufn[0+0-:1];
    end else begin
      if (a == 1'h1 & b == 1'h0) begin
        holder = alufn[1+0-:1];
      end else begin
        if (a == 1'h0 & b == 1'h1) begin
          holder = alufn[2+0-:1];
        end else begin
          holder = alufn[3+0-:1];
        end
      end
    end
    bool = holder;
  end
endmodule
