/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_9 (
    input [2:0] alufn,
    input z,
    input v,
    input n,
    output reg [15:0] result
  );
  
  
  
  reg holder;
  
  always @* begin
    if (alufn[2+0-:1] == 1'h0 & alufn[1+0-:1] == 1'h1) begin
      holder = z;
    end else begin
      if (alufn[2+0-:1] == 1'h1 & alufn[1+0-:1] == 1'h0) begin
        holder = n ^ v;
      end else begin
        holder = z | (n ^ v);
      end
    end
    result[0+0-:1] = holder;
    result[1+14-:15] = 15'h0000;
  end
endmodule
