/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_10 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] result
  );
  
  
  
  wire [16-1:0] M_mul_out;
  reg [16-1:0] M_mul_a;
  reg [16-1:0] M_mul_b;
  reg [6-1:0] M_mul_alufn;
  multiplier_11 mul (
    .a(M_mul_a),
    .b(M_mul_b),
    .alufn(M_mul_alufn),
    .out(M_mul_out)
  );
  
  always @* begin
    M_mul_a = a;
    M_mul_b = b;
    M_mul_alufn = alufn;
    
    case (alufn[0+1-:2])
      2'h0: begin
        result = a << b[0+3-:4];
      end
      2'h1: begin
        result = a >> b[0+3-:4];
      end
      2'h3: begin
        result = $signed(a) >>> b[0+3-:4];
      end
      2'h2: begin
        result = M_mul_out;
      end
      default: begin
        result = 1'h0;
      end
    endcase
  end
endmodule
